Quiron.LojaVirtual.Web/Models/CarrinhoViewModel.cs
using Quiron.LojaVirtual.Dominio.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Quiron.LojaVirtual.Web.Models
{
    public class CarrinhoViewModel
    {
        public Carrinho Carrinho { get; set; }
        public string ReturnUrl { get; set; }        
    }
}

Quiron.LojaVirtual.Web/Models/Paginacao.cs
using System;

namespace Quiron.LojaVirtual.Web.Models
{
    public class Paginacao
    {
        public int ItensTotal { get; set; }
        public int ItensPorPagina { get; set; }
        public int PaginaAtual { get; set; }
        public int TotalPaginas 
        {
            get
            {
                return (int) Math.Ceiling((decimal) ItensTotal / ItensPorPagina);
            }
        }

    }
}

Quiron.LojaVirtual.Web/Models/ProdutosViewModel.cs
using Quiron.LojaVirtual.Dominio.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Quiron.LojaVirtual.Web.Models
{
    public class ProdutosViewModel
    {
        public IEnumerable<Produto> Produtos { get; set; }

        public Paginacao Paginacao { get; set; }

        public string CategoriaAtual { get; set; }


    }
}

Quiron.LojaVirtual.Web/Controllers/CarrinhoController.cs
using Quiron.LojaVirtual.Dominio.Entidades;
using Quiron.LojaVirtual.Dominio.Repositorio;
using Quiron.LojaVirtual.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class CarrinhoController : Controller
    {
        private ProdutosRepositorio repositorio;

        public ViewResult Index(string returnUrl)        
        {
            return View(new CarrinhoViewModel { Carrinho = ObterCarrinho(), ReturnUrl = returnUrl });
        }
        
        // GET: Carrinho
        public RedirectToRouteResult Adicionar(int produtoId, string returnUrl)
        {
            repositorio = new ProdutosRepositorio();

            Produto produto = repositorio.Produtos.FirstOrDefault(p => p.ProdutoId == produtoId);

            if (produto != null)
            {
                ObterCarrinho().AdicionarItem(produto, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        private Carrinho ObterCarrinho()
        {
            Carrinho carrinho = (Carrinho) Session["Carrinho"];

            if (carrinho == null)
            {
                carrinho = new Carrinho();
                Session["Carrinho"] = carrinho;
            }

            return carrinho;
        }

        public RedirectToRouteResult Remover(int produtoId, string returnUrl)
        {
            repositorio = new ProdutosRepositorio();

            Produto produto = repositorio.Produtos.FirstOrDefault(p => p.ProdutoId == produtoId);

            if (produto != null)
            {
                ObterCarrinho().RemoverItem(produto);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Resumo()
        {
            Carrinho carrinho = ObterCarrinho();
            return PartialView(carrinho);
        }
    }
}

Quiron.LojaVirtual.Web/Controllers/VitrineController.cs
using Quiron.LojaVirtual.Dominio.Repositorio;
using Quiron.LojaVirtual.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class VitrineController : Controller
    {
        private ProdutosRepositorio repositorio;
        private int produtosPorPagina = 8;
        
        // GET: Vitrine
        public ActionResult ListarProdutos(string categoria, int pagina)
        {
            repositorio = new ProdutosRepositorio();            

            ProdutosViewModel model = new ProdutosViewModel()
            {
                Produtos = repositorio.Produtos
                    .Where(p => categoria == null || p.Categoria == categoria)
                    .OrderBy(p => p.Descricao)
                    .Skip((pagina - 1) * produtosPorPagina)
                    .Take(produtosPorPagina),
                
                Paginacao = new Paginacao()
                {
                    PaginaAtual = pagina,
                    ItensPorPagina = produtosPorPagina,
                    ItensTotal = categoria == null ? repositorio.Produtos.Count() : repositorio.Produtos.Where(p => p.Categoria == categoria).Count()
                },
                
                CategoriaAtual = categoria
            };            

            return View(model);
        }

    }
}

Quiron.LojaVirtual.Web/Views/Carrinho/Resumo.cshtml
@model Quiron.LojaVirtual.Dominio.Entidades.Carrinho

<style>
    #botaozinho a {
        margin-right: 20%;
    }
</style>

<div id="botaozinho" class="navbar-right">
    @Html.ActionLink("Checkout", "Index", "Carrinho", new { returnUrl = Request.Url.PathAndQuery }, new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-text navbar-right">
    <strong>Seus produtos:</strong> @Model.ItensCarrinho.Sum(x => x.Quantidade) item(s), @Model.ObterValorTotal().ToString("c")
</div>

Quiron.LojaVirtual.Web/Views/Categoria/Menu.cshtml
@model System.Collections.Generic.IEnumerable<string>

@Html.ActionLink("Todos os produtos", "ListarProdutos", "Vitrine", null, new { @class = "btn btn-block btn-default btn-lg active"})


@foreach (string item in Model)
{    
    @Html.RouteLink(item, 
                    new { controller = "Vitrine", action = "ListarProdutos", categoria = item, pagina = 1 }, 
                    new { @class = "btn btn-block btn-lg active "  + (ViewBag.CategoriaSelecionada == item ? "btn-primary" : "btn-default")})
    //@Html.ActionLink(item, "ListarProdutos", "Vitrine", new { categoria = item }, new { @class = "btn btn-block btn-primary btn-lg" })
}

Quiron.LojaVirtual.Web/Views/Produtos/Index.cshtml
@model IEnumerable<Quiron.LojaVirtual.Dominio.Entidades.Produto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categoria)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProdutoId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProdutoId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProdutoId })
        </td>
    </tr>
}

</table>

Quiron.LojaVirtual.Web/Views/Shared/ProdutoDetalhes.cshtml
@model Quiron.LojaVirtual.Dominio.Entidades.Produto

<div class="well">
    <h3><strong>@Model.Nome</strong></h3>

    <h3><span class="pull-right label label-primary">@Model.Preco.ToString("c")</span></h3>

    @using (Html.BeginForm("Adicionar", "Carrinho"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProdutoId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Comprar"/>
        </div> 
    }

    <h3><span class="lead">@Model.Descricao</span></h3>
</div>

Quiron.LojaVirtual.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Quiron Loja Virtual</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <a class="navbar-brand" href="#">Quiron Loja Virtual - Seu esporte é aqui</a>
        @Html.Action("Resumo", "Carrinho")
    </div>
    <hr />

    <div class="row panel">

        <div id="categoria" class="col-xs-3">
            @Html.Action("Menu", "Categoria")
        </div>

        <div id="produtos" class="col-xs-8">
            @RenderBody()
        </div>

    </div>
</body>
</html>

Quiron.LojaVirtual.Web/Views/Vitrine/ListarProdutos.cshtml
@model Quiron.LojaVirtual.Web.Models.ProdutosViewModel
@using Quiron.LojaVirtual.Web.HtmlHelpers

@foreach (var produto in Model.Produtos)
{
    @Html.Partial("ProdutoDetalhes", produto);
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.Paginacao, x => Url.Action("ListarProdutos", new { pagina = x, categoria = Model.CategoriaAtual}))
</div>